
/*
 * Structures for model: ng_int_rst
 *
 * Automatically generated by cmpp preprocessor
 *
 * !!! DO NOT EDIT !!!
 *
 */


#include "ngspice/ngspice.h"
#include <stdio.h>
#include "ngspice/devdefs.h"
#include "ngspice/ifsim.h"
#include "ngspice/mifdefs.h"
#include "ngspice/mifproto.h"
#include "ngspice/mifparse.h"


static IFparm MIFmPTable[] = {
    IOP("mode", 0, IF_INTEGER, "reset mode"),
    IOP("ic", 1, IF_REAL, "initial cond"),
    IOP("gain", 2, IF_REAL, "input gain"),
    IOP("vth", 3, IF_REAL, "threshold"),
    IOP("vhyst", 4, IF_REAL, "hysteresis"),
    IOP("lo", 5, IF_REAL, "lower limit"),
    IOP("hi", 6, IF_REAL, "upper limit"),
    IOP("limit_range", 7, IF_REAL, "limit smoothing"),
    IOP("aw_enable", 8, IF_FLAG, "anti-windup enable"),
};


static Mif_Port_Type_t MIFportEnum0[] = {
    MIF_VOLTAGE,
};


static char *MIFportStr0[] = {
    "v",
};


static Mif_Port_Type_t MIFportEnum1[] = {
    MIF_VOLTAGE,
};


static char *MIFportStr1[] = {
    "v",
};


static Mif_Port_Type_t MIFportEnum2[] = {
    MIF_VOLTAGE,
};


static char *MIFportStr2[] = {
    "v",
};


static Mif_Conn_Info_t MIFconnTable[] = {
  {
    "in",
    "input",
    MIF_IN,
    MIF_VOLTAGE,
    "v",
    1,
    MIFportEnum0,
    MIFportStr0,
    MIF_FALSE,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_FALSE,
  },
  {
    "rst",
    "reset",
    MIF_IN,
    MIF_VOLTAGE,
    "v",
    1,
    MIFportEnum1,
    MIFportStr1,
    MIF_FALSE,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_FALSE,
  },
  {
    "out",
    "output",
    MIF_OUT,
    MIF_VOLTAGE,
    "v",
    1,
    MIFportEnum2,
    MIFportStr2,
    MIF_FALSE,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_FALSE,
  },
};

static union Mif_Parse_Value mode_default[] = {
    { .ivalue=1 },
};

static union Mif_Parse_Value ic_default[] = {
    { .rvalue=0.000000e+00 },
};

static union Mif_Parse_Value gain_default[] = {
    { .rvalue=1.000000e+00 },
};

static union Mif_Parse_Value vth_default[] = {
    { .rvalue=5.000000e-01 },
};

static union Mif_Parse_Value vhyst_default[] = {
    { .rvalue=0.000000e+00 },
};

static union Mif_Parse_Value lo_default[] = {
    { .rvalue=-1.000000e+12 },
};

static union Mif_Parse_Value hi_default[] = {
    { .rvalue=1.000000e+12 },
};

static union Mif_Parse_Value limit_range_default[] = {
    { .rvalue=1.000000e-09 },
};

static union Mif_Parse_Value aw_enable_default[] = {
    { .bvalue=MIF_FALSE },
};


static Mif_Param_Info_t MIFparamTable[] = {
  {
    "mode",
    "reset mode",
    MIF_INTEGER,
    1,
    mode_default,
    MIF_TRUE,
    { .ivalue=0 },
    MIF_TRUE,
    { .ivalue=2 },
    MIF_FALSE,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_TRUE,
  },
  {
    "ic",
    "initial cond",
    MIF_REAL,
    1,
    ic_default,
    MIF_FALSE,
    { .bvalue=MIF_FALSE },
    MIF_FALSE,
    { .bvalue=MIF_FALSE },
    MIF_FALSE,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_TRUE,
  },
  {
    "gain",
    "input gain",
    MIF_REAL,
    1,
    gain_default,
    MIF_FALSE,
    { .bvalue=MIF_FALSE },
    MIF_FALSE,
    { .bvalue=MIF_FALSE },
    MIF_FALSE,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_TRUE,
  },
  {
    "vth",
    "threshold",
    MIF_REAL,
    1,
    vth_default,
    MIF_FALSE,
    { .bvalue=MIF_FALSE },
    MIF_FALSE,
    { .bvalue=MIF_FALSE },
    MIF_FALSE,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_TRUE,
  },
  {
    "vhyst",
    "hysteresis",
    MIF_REAL,
    1,
    vhyst_default,
    MIF_TRUE,
    { .rvalue=0.000000e+00 },
    MIF_FALSE,
    { .bvalue=MIF_FALSE },
    MIF_FALSE,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_TRUE,
  },
  {
    "lo",
    "lower limit",
    MIF_REAL,
    1,
    lo_default,
    MIF_FALSE,
    { .bvalue=MIF_FALSE },
    MIF_FALSE,
    { .bvalue=MIF_FALSE },
    MIF_FALSE,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_TRUE,
  },
  {
    "hi",
    "upper limit",
    MIF_REAL,
    1,
    hi_default,
    MIF_FALSE,
    { .bvalue=MIF_FALSE },
    MIF_FALSE,
    { .bvalue=MIF_FALSE },
    MIF_FALSE,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_TRUE,
  },
  {
    "limit_range",
    "limit smoothing",
    MIF_REAL,
    1,
    limit_range_default,
    MIF_TRUE,
    { .rvalue=0.000000e+00 },
    MIF_FALSE,
    { .bvalue=MIF_FALSE },
    MIF_FALSE,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_TRUE,
  },
  {
    "aw_enable",
    "anti-windup enable",
    MIF_BOOLEAN,
    1,
    aw_enable_default,
    MIF_FALSE,
    { .bvalue=MIF_FALSE },
    MIF_FALSE,
    { .bvalue=MIF_FALSE },
    MIF_FALSE,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_TRUE,
  },
};


extern void ucm_ng_int_rst(Mif_Private_t *);

static int val_terms             = 0;
static int val_numNames          = 0;
static int val_numInstanceParms  = 0;
static int val_numModelParms     = 9;
static int val_sizeofMIFinstance = sizeof(MIFinstance);
static int val_sizeofMIFmodel    = sizeof(MIFmodel);

SPICEdev ucm_ng_int_rst_info = {
    .DEVpublic = {
        .name = "ng_int_rst",
        .description = "resettable integrator",
        .terms = &val_terms,
        .numNames = &val_numNames,
        .termNames = NULL,
        .numInstanceParms = &val_numInstanceParms,
        .instanceParms = NULL,
        .numModelParms = &val_numModelParms,
        .modelParms = MIFmPTable,
        .flags = 0,

        .cm_func = ucm_ng_int_rst,
        .num_conn = 3,
        .conn = MIFconnTable,
        .num_param = 9,
        .param = MIFparamTable,
        .num_inst_var = 0,
        .inst_var = NULL,
    },

    .DEVparam = NULL,
    .DEVmodParam = MIFmParam,
    .DEVload = MIFload,
    .DEVsetup = MIFsetup,
    .DEVunsetup = MIFunsetup,
    .DEVpzSetup = NULL,
    .DEVtemperature = NULL,
    .DEVtrunc = MIFtrunc,
    .DEVfindBranch = NULL,
    .DEVacLoad = MIFload,
    .DEVaccept = NULL,
    .DEVdestroy = NULL,
    .DEVmodDelete = MIFmDelete,
    .DEVdelete = MIFdelete,
    .DEVsetic = NULL,
    .DEVask = MIFask,
    .DEVmodAsk = MIFmAsk,
    .DEVpzLoad = NULL,
    .DEVconvTest = MIFconvTest,
    .DEVsenSetup = NULL,
    .DEVsenLoad = NULL,
    .DEVsenUpdate = NULL,
    .DEVsenAcLoad = NULL,
    .DEVsenPrint = NULL,
    .DEVsenTrunc = NULL,
    .DEVdisto = NULL,
    .DEVnoise = NULL,
    .DEVsoaCheck = NULL,
    .DEVinstSize = &val_sizeofMIFinstance,
    .DEVmodSize = &val_sizeofMIFmodel,

#ifdef CIDER
    .DEVdump = NULL,
    .DEVacct = NULL,
#endif

#ifdef KLU
    .DEVbindCSC = NULL,
    .DEVbindCSCComplex = NULL,
    .DEVbindCSCComplexToReal = NULL,
#endif
};

